export const SEND_STRING = 'SEND_STRING';
export const CHANGE_STRING = 'CHANGE_STRING';
export const ADD_STRING_SUCCESS = 'ADD_STRING_SUCCESS';
export const ADD_STRING_ERROR = 'ADD_STRING_ERROR';
export const RESET_STRING_FORM = 'RESET_STRING_FORM';
