export const SET_STRINGS = 'SET_STRINGS';
export const GET_STRINGS = 'GET_STRINGS';
export const GET_STRINGS_ERROR = 'GET_STRINGS_ERROR';
export const LOADING_STRINGS = 'LOADING_STRINGS';
export const RESET_STRING_PAGE = 'RESET_STRING_PAGE';
